///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
///
int counter = 1;

class ZYHomeListItemModel {
/*
{
  "title": "#查处罂粟种植 山东烟台，民警铲除非法种植的罂粟，一家小院里种了60多株！",
  "share_url": "https://www.iesdouyin.com/share/video/6963446422419033344/?region=CN&mid=6599908656580561667&u_code=0&titleType=title&did=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&with_sec_did=1",
  "author": "生活帮",
  "item_cover": "https://p29.douyinpic.com/img/tos-cn-p-0015/31836ad29d4c469c91f00679073b233f~c5_300x400.jpeg?from=2563711402_large",
  "hot_value": 211153599,
  "hot_words": "查处,罂粟,种植,山东,烟台,民警,铲除,非法,一家,院里,60,多株",
  "play_count": 266884111,
  "digg_count": 2225435,
  "comment_count": 7
}
*/
  int rank = 0;
  String title;
  String shareUrl;
  String author;
  String itemCover;
  int hotValue;
  String hotWords;
  int playCount;
  int diggCount;
  int commentCount;
  double rating;

  ZYHomeListItemModel({
    this.title,
    this.shareUrl,
    this.author,
    this.itemCover,
    this.hotValue,
    this.hotWords,
    this.playCount,
    this.diggCount,
    this.commentCount,
  });

  ZYHomeListItemModel.fromJson(Map<String, dynamic> json) {
    rank = counter++;
    title = json["title"]?.toString();
    shareUrl = json["share_url"]?.toString();
    author = json["author"]?.toString();
    itemCover = json["item_cover"]?.toString();
    hotValue = json["hot_value"]?.toInt();
    hotWords = json["hot_words"]?.toString();
    playCount = json["play_count"]?.toInt();
    diggCount = json["digg_count"]?.toInt();
    commentCount = json["comment_count"]?.toInt();

    if (title == null || title.isEmpty) {
      title = "我是拼接的";
    }
    print("title:$title");
    rating = double.parse(hotValue.toString().substring(0, 1)) +
        double.parse(hotValue.toString().substring(1, 2));

    if (rating > 10) {
      rating = (rating / 2) as double;
    } else if (rating < 3) {
      rating += 6.4;
    } else if (rating < 5) {
      rating += 3.9;
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["title"] = title;
    data["share_url"] = shareUrl;
    data["author"] = author;
    data["item_cover"] = itemCover;
    data["hot_value"] = hotValue;
    data["hot_words"] = hotWords;
    data["play_count"] = playCount;
    data["digg_count"] = diggCount;
    data["comment_count"] = commentCount;
    return data;
  }

  @override
  String toString() {
    return 'ZYHomeListItemModel{title: $title, shareUrl: $shareUrl, author: $author, itemCover: $itemCover, hotValue: $hotValue, hotWords: $hotWords, playCount: $playCount, diggCount: $diggCount, commentCount: $commentCount}';
  }
}

class ZYHomeListModel {
/*
{
  "reason": "查询成功",
  "result": [
    {
      "title": "#查处罂粟种植 山东烟台，民警铲除非法种植的罂粟，一家小院里种了60多株！",
      "share_url": "https://www.iesdouyin.com/share/video/6963446422419033344/?region=CN&mid=6599908656580561667&u_code=0&titleType=title&did=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&with_sec_did=1",
      "author": "生活帮",
      "item_cover": "https://p29.douyinpic.com/img/tos-cn-p-0015/31836ad29d4c469c91f00679073b233f~c5_300x400.jpeg?from=2563711402_large",
      "hot_value": 211153599,
      "hot_words": "查处,罂粟,种植,山东,烟台,民警,铲除,非法,一家,院里,60,多株",
      "play_count": 266884111,
      "digg_count": 2225435,
      "comment_count": 7
    }
  ],
  "error_code": 0
}
*/

  String reason;
  List<ZYHomeListItemModel> result;
  int errorCode;

  ZYHomeListModel({
    this.reason,
    this.result,
    this.errorCode,
  });

  ZYHomeListModel.fromJson(Map<String, dynamic> json) {
    reason = json["reason"]?.toString();
    if (json["result"] != null) {
      final v = json["result"];
      final arr0 = <ZYHomeListItemModel>[];
      v.forEach((v) {
        arr0.add(ZYHomeListItemModel.fromJson(v));
      });
      result = arr0;
    }
    errorCode = json["error_code"]?.toInt();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["reason"] = reason;
    if (result != null) {
      final v = result;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["result"] = arr0;
    }
    data["error_code"] = errorCode;
    return data;
  }

  @override
  String toString() {
    return 'ZYHomeListModel{reason: $reason, result: $result, errorCode: $errorCode}';
  }
}
